### ISSUE TITLE
「CSSによる配置（配置）」のコードが画像と対応していない

### ISSUE THREAD

**Issue by tknkaa** [ut-code/utcode-learn#839]
CSS による配置（発展）の [position](https://learn.utcode.net/docs/browser-apps/css-arrangement/#position) の章で、index.html や style.css に書かれているコードと画像が一致していないかと思われます。画像に合わせるなら、
```html
<!-- index.html -->
<body>
  <div class="box1">box1</div>
  <div class="box2">box2</div>
  <div class="box3">box3</div>
</body>
```

``` css
/* style.css */
.box1 {
  width: 200px;
  height: 200px;
  background-color: lightcoral;
}

.box2 {
  position: relative;
  top: 50px;
  left: 50px;
  width: 200px;
  height: 200px;
  background-color: lightblue;
}

.box3 {
  width: 200px;
  height: 200px;
  background-color: lightgreen;
}
```
